apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "release-board.fullname" . }}-api
  labels:
    {{- include "release-board.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "release-board.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api