apiVersion: v1
kind: Service
metadata:
  name: {{ include "release-board.fullname" . }}-postgres
  labels:
    {{- include "release-board.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "release-board.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP