apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "release-board.fullname" . }}-api
  labels:
    {{- include "release-board.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
automountServiceAccountToken: false